### ISSUE TITLE
Error when calling ffmpeg from OFS plugin

### ISSUE THREAD

**Issue by Zalunda** [Zalunda/FunscriptToolbox#3]
![image](https://user-images.githubusercontent.com/8295521/222833674-4789858e-66c1-48fc-88d5-0eea4cb724b9.png)

**Comment by transmissionended** [comment]
Actions do get generated when UI is unchecked.

Also, PrepareVideoForOFS seems to encounter the same error.
![image](https://user-images.githubusercontent.com/126937143/222876997-27936b9c-1ff2-48f1-a163-8693541dba9c.png)

**Comment by Zalunda** [comment]
Thanks. I'm preparing a new version with a few small fixes for what has been found so far. 
It won't include a fix your problem because, honestly, I don't really have an idea what to do so far.
But I'll add some bypass. For example, if I can't extract an image, I'll still show the UI but it will be a black screen + green arrows. I'll also write in FunscriptToolbox.log the exact command that I'm running in ffmpeg. You should be able to run them yourself.

The last point that I'm curious about: 
In OFS, there is also an action that makes a call ffmpeg. I'm curious to see if it works for you.

Can you try right-clicking in the timeline and selecting "Update Waveform"? Do you get the waveform a little bit later?
![Untitled](https://user-images.githubusercontent.com/8295521/222917933-9e1711ac-df75-4cc8-8339-b3e6b810149d.jpg)

**Comment by transmissionended** [comment]
Yes the waveform does appear for me when selecting "Update Waveform".
![image](https://user-images.githubusercontent.com/126937143/222924493-1820321e-9afd-4f8e-8c79-c4fb44e36523.png)

**Comment by transmissionended** [comment]
It seems to be an issue with the specific version of ffmpeg.exe that was included in the 1.2.1 release. I've managed to avoid the issue by trying other versions.

**Comment by Zalunda** [comment]
It's great that you found something but did you revert to FunscriptToolBox 1.2.1 to 1.2.0 and use the same version of ffmpeg (same size and all)?
Or revert the version ffmpeg? If yes, and you still have the 'bad' version of ffmpeg, can you link it here?
Because I don't include ffmpeg directly inside my application. I'm using an auto downloader that always downloads the latest version to %appdata\ffmpeg, using FFmpegDownloader.GetLatestVersion(FFmpegVersion.Official).

Anyway, it's great that it works. Let me know if it breaks again when I release 1.2.2. It shouldn't be too hard to figure out which change is creating problem.

**Comment by transmissionended** [comment]
I only updated the ffmpeg version I had in order to get around the error. Everything seems to work fine now with ffmpeg 6.0 after grabbing the latest version myself. The version I had after FunscriptToolbox installation was "4.4.1-full_build-www.gyan.dev". I don't know what version you're expecting the autodownload to get but 4.4.1 seems a bit old to me, so my current theory is something failed in the auto-download/install process and the ffmpeg version I had after was actually from a earlier install of an older version of FunscriptToolbox. 

No issues with FunscriptToolBox 1.2.2 either btw.

**Comment by Zalunda** [comment]
Great. And you are right that it seems like an old version. I might go back to my own code to download ffmpeg. I switched because it was more convenient to use the library from xabe.ffmpeg but I didn't notice that their source was older.

Xabe uses this source: https://ffbinaries.com/ (http://ffbinaries.com/api/v1/version/latest)
It has the advantage to download the right version for each OS but, in my case, I'm only interested in the version Windows.

Anyway, I'll close the bug for now.
